### ISSUE TITLE
SignalHandler class is missing

### ISSUE THREAD

**Issue by murogrande** [murogrande/Snake-terminal#4]
Hi @a-quelle, I would like to run the game (in the branch aq/refactor) but I have the following error:

game.cpp: In constructor ‘Game::Game()’:
game.cpp:20:42: error: missing template arguments before ‘(’ token

     auto finished_handler = SignalHandler(this, &Game::title_screen_finished);

The part of the code is in line 18 of the file:

Game::Game()
{
    auto finished_handler = **SignalHandler(this, &Game::title_screen_finished);**
    levels.emplace_back(std::make_shared<TitleScreen>(gamestate, finished_handler));
    levels.emplace_back(std::make_shared<SnakeGame>(gamestate));
    Terminal::instance().show_cursor(false);
}

The same problem is in the main_game branch. It is in the game.cpp file. 

What I can do ?

**Comment by a-quelle** [comment]
That code comes from the branch aq/main_game
I wanted to get into the signal stuff later, since it's a bit tricky.

The game class should look like
`Game::Game()
{
    levels.emplace_back(std::make_shared<TitleScreen>(gamestate));
    Terminal::instance().show_cursor(false);
}`

If you don't remember how you got the code in this state, you can always just reset your branch.
